services:
  adguardhome:
    image: adguard/adguardhome
    restart: unless-stopped

    network_mode: host

    volumes:
      - /srv/docker/adguardhome/conf:/opt/adguardhome/conf
      - /srv/docker/adguardhome/work:/opt/adguardhome/work
