services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped

    expose:
      - "3000"

    volumes:
      - /srv/docker/homepage/config:/app/config

    environment:
      HOMEPAGE_ALLOWED_HOSTS: "home.lab.gabrielro.com"

    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
