services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped

    expose:
      - "3000"

    volumes:
      - /srv/docker/homepage/config:/app/config
      - /opt/homelab/docker/homepage/assets:/app/public/assets:ro

    environment:
      HOMEPAGE_ALLOWED_HOSTS: "home.lab.gabrielro.com"

    dns:
      - 192.168.1.55

    networks:
      - proxy-net

    env_file:
      - .env

networks:
  proxy-net:
    external: true